
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.91:2200/jtest001?useUnicode=true&characterEncoding=utf-8
    username: SCS
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.jsen.test.entity
  global-config:
    logic-delete-value: -1
    logic-not-delete-value: 1
    sql-parser-cache: true


# log config
logging:
  config: classpath:logback.xml
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin
    executor:
      ### xxl-job executor address
      appname: xxl-job-executor-sample
      ip:
      port: 9999

      ### xxl-job log path
      logpath: /Users/jsen/data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1

    ### xxl-job, access token
    accessToken:

