
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtest001?useUnicode=true&characterEncoding=utf-8
    username: root
    password:

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.jsen.test.entity
  global-config:
    logic-delete-value: -1
    logic-not-delete-value: 1
    sql-parser-cache: true